controller_manager_ns: controller_manager

controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - S1
      - S2
      - E1
      - E2
      - W1
      - W2
      - W3

  - name: gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - finger_joint_1
      - finger_joint_2

